# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjQxNjIyYTc1YTdhNzM1ODUwOTQ2OGM0MzZkN2Y2NGM3MDdkOGIzOThjZjBlZDI1ZjBmNWYzOTU2MzhjNTk2YmU1M2U3YmY1YTJjMzA0YmU1ZjY1OTQwNzIxYWIwNDNjOTk4NjdhYTY4M2RjY2JhMjMzNjUyNjU2ZTg2YjliMGY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
